# - name: Ensure Load Balancer configuration 
#   azure_rm_loadbalancer:
#     resource_group: "{{ rg_name }}"
#     name: "{{ loadbalancer_name }}"
#     location: "{{ location }}"
#     frontend_ip_configurations:
#       - name: frontendipconf0
#         public_ip_address: "{{ loadbalancer_name }}-public-ip"
#     backend_address_pools:
#       - name: "{{ loadbalancer_backend_address_pool_name }}"
#     probes:
#       - name: prob0
#         port: 80
#     inbound_nat_pools:
#       - name: inboundnatpool0
#         frontend_ip_configuration_name: frontendipconf0
#         protocol: Tcp
#         frontend_port_range_start: 80
#         frontend_port_range_end: 81
#         backend_port: 8080
    # load_balancing_rules:
    #   - name: lbrbalancingrule0
    #     frontend_ip_configuration: frontendipconf0
    #     backend_address_pool: backendaddrpool0
    #     frontend_port: 80
    #     backend_port: 80
    #     probe: prob0
    # inbound_nat_rules:
    #   - name: inboundnatrule0
    #     backend_port: 8080
    #     protocol: Tcp
    #     frontend_port: 8080
    #     frontend_ip_configuration: frontendipconf0