- name: Create resource group
  azure_rm_resourcegroup:
    name: "{{ rg_name }}"
    location: "{{ location }}"

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{ rg_name }}"
    name: "{{ vnet_name }}"
    address_prefixes: "{{ vnet_prefix }}"

- name: Create subnet
  azure_rm_subnet:
    resource_group: "{{ rg_name }}"
    name: "{{ subnet_name }}"
    address_prefix: "{{ subnet_prefix }}"
    virtual_network: "{{ vnet_name }}"


- name: Create Network Security Group
  azure_rm_securitygroup:
    resource_group: "{{ rg_name }}"
    name: "{{ nsg_name }}"
    rules:
      - name: 'allow_web_traffic'
        priority: 1002
        protocol: Tcp
        access: Allow
        direction: Inbound
        destination_port_range:
            - 80
            - 443        
      - name: 'allow_ssh_remote'
        priority: 1003
        protocol: Tcp
        access: Allow
        direction: Inbound
        destination_port_range: 
            - 22
        source_address_prefix:
          - "{{ ansible_remote_control_ip }}"

- name: Create public IP address for Load Balancer
  azure_rm_publicipaddress:
    resource_group: "{{ rg_name }}"
    allocation_method: dynamic
    name: "{{ loadbalancer_name }}-public-ip"

- name: Create Load Balancer with basic setting but not configured
  azure_rm_loadbalancer:
    resource_group: "{{ rg_name }}"
    name: "{{ loadbalancer_name }}"
    location: "{{ location }}"
    frontend_ip_configurations:
      - name: frontendipconf0
        public_ip_address: "{{ loadbalancer_name }}-public-ip"
    backend_address_pools:
      - name: "{{ loadbalancer_backend_address_pool_name }}"
  register: lb_result
  tags: 
    - lb
    - nic
