---
    - name: Install Python and its required dependencies
      yum: 
        name: "{{ item }}"
        state: installed 
      with_items:
        - python3
        - python3-setuptools
        - platform-python-devel
        #- build-essential
        - python3-pip
        #- python3-mysqldb
        - git