---
    - name: Install MySQL database
      yum: 
        name: "{{ item }}"
        state: installed 
      with_items:
        - mysql-server
        - mysql

    - name: Install PyMysql  dependency
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - pymysql

    - name: Update MySQL Configuration file to accept connections from all interfaces instead of default loopback only
      ini_file:
        path: /etc/mysql/my.cnf
        section: mysqld
        option: bind-address
        value: 0.0.0.0

    - name: Start MySQL Service
      service:
        name: mysqld
        state: started
        enabled: yes

    - name: Create Application Database
      mysql_db: 
        name: "{{ db_name }}"
        state: present

    - name: Create Database user
      mysql_user:
        name: "{{ db_user }}"
        password: "{{ db_user_password }}"
        priv: '*.*:ALL'
        state: present
        host: '%'

    - name: Re-start MySQL Service
      service:
        name: mysqld
        state: restarted
        enabled: yes